// Auxiliary profile used exclusively by the pump duty calibration tool.
// Embedded rather than loaded from the machine so runs are reproducible.
//
// The measure phase carries `pump` as a bare integer. profile.h:296 reads that
// into pumpIsSimple/pumpSimple, BrewProcess::getPumpValue returns it unchanged,
// and Controller::updateControl routes it to PumpControlMode::Power, so the
// pump holds a fixed duty with no feedback of any kind. An object-valued pump
// would be parsed as an advanced flow or pressure target instead, which is
// exactly the closed loop this experiment has to avoid.

export const DUTY_PROFILE_ID = 'pump-duty-calibration';
export const DEFAULT_MEASURE_SECONDS = 45;

export function buildDutyProfile(dutyPercent, measureSeconds = DEFAULT_MEASURE_SECONDS) {
  const duty = Math.max(0, Math.min(100, Math.round(dutyPercent)));
  return {
    id: DUTY_PROFILE_ID,
    label: `[Calibration] Pump duty ${duty}%`,
    type: 'pro',
    description: 'Auto-generated by the pump duty calibration tool.',
    temperature: 30,
    phases: [
      {
        name: 'Prepare',
        phase: 'preinfusion',
        valve: 0,
        duration: 5,
        temperature: 0,
        transition: { type: 'instant', duration: 0, adaptive: true },
        pump: 0,
      },
      {
        name: `Measure ${duty}`,
        phase: 'brew',
        valve: 0,
        duration: measureSeconds,
        temperature: 0,
        transition: { type: 'instant', duration: 0, adaptive: true },
        pump: duty,
      },
    ],
  };
}
